#pragma once

#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_BUTTON_TRIGGER_ON_RELEASE

#ifdef OS_WEBOS
#ifndef WEBOS_LEGACY
#define NK_SDL_GLES2
#else
#define NK_LGNC_GLES2
#endif
#else
#define NK_SDL_GL2
#endif