#pragma once

#define SDL_WEBOS_SCANCODE_BACK 482
#define SDL_WEBOS_SCANCODE_CURSOR_SHOW 484
#define SDL_WEBOS_SCANCODE_CURSOR_HIDE 485
#define SDL_WEBOS_SCANCODE_RED 486
#define SDL_WEBOS_SCANCODE_GREEN 487
#define SDL_WEBOS_SCANCODE_YELLOW 488
#define SDL_WEBOS_SCANCODE_BLUE 489