#pragma once

#define BS_SYMBOL_ADD_TO_QUEUE "\xee\x81\x9c"
#define BS_SYMBOL_ARROW_DROP_DOWN "\xee\x97\x85"
#define BS_SYMBOL_CHECK "\xee\x97\x8a"
#define BS_SYMBOL_CLOSE "\xee\x97\x8d"
#define BS_SYMBOL_DESKTOP_WINDOWS "\xee\x8c\x8c"
#define BS_SYMBOL_HELP "\xee\xa2\x87"
#define BS_SYMBOL_INFO "\xee\xa2\x8e"
#define BS_SYMBOL_LOCK "\xee\xa2\x97"
#define BS_SYMBOL_ONDEMAND_VIDEO "\xee\x98\xba"
#define BS_SYMBOL_PLAY_ARROW "\xee\x80\xb7"
#define BS_SYMBOL_PUSH_PIN "\xef\x84\x8d"
#define BS_SYMBOL_SETTINGS "\xee\xa2\xb8"
#define BS_SYMBOL_SPORTS_ESPORTS "\xee\xa8\xa8"
#define BS_SYMBOL_TUNE "\xee\x90\xa9"
#define BS_SYMBOL_TV "\xee\x8c\xb3"
#define BS_SYMBOL_VIDEO_SETTINGS "\xee\xa9\xb5"
#define BS_SYMBOL_WARNING "\xee\x80\x82"
