#pragma once

#include "Limelight.h"

extern AUDIO_RENDERER_CALLBACKS ss4s_aud_callbacks;

#define CALLBACKS_SESSION_ERROR_VDEC_UNSUPPORTED 9001
#define CALLBACKS_SESSION_ERROR_VDEC_ERROR 9002
#define CALLBACKS_SESSION_ERROR_ADEC_UNSUPPORTED 10001
#define CALLBACKS_SESSION_ERROR_ADEC_ERROR 10002
