#pragma once

#define MAT_SYMBOL_ADD_TO_QUEUE "\xee\x81\x9c"
#define MAT_SYMBOL_ARROW_DROP_DOWN "\xee\x97\x85"
#define MAT_SYMBOL_CHECK "\xee\x97\x8a"
#define MAT_SYMBOL_CLOSE "\xee\x97\x8d"
#define MAT_SYMBOL_DESKTOP_WINDOWS "\xee\x8c\x8c"
#define MAT_SYMBOL_HELP "\xee\xa2\x87"
#define MAT_SYMBOL_INFO "\xee\xa2\x8e"
#define MAT_SYMBOL_LOCK "\xee\xa2\x97"
#define MAT_SYMBOL_ONDEMAND_VIDEO "\xee\x98\xba"
#define MAT_SYMBOL_PLAY_ARROW "\xee\x80\xb7"
#define MAT_SYMBOL_PUSH_PIN "\xef\x84\x8d"
#define MAT_SYMBOL_SETTINGS "\xee\xa2\xb8"
#define MAT_SYMBOL_SPORTS_ESPORTS "\xee\xa8\xa8"
#define MAT_SYMBOL_TUNE "\xee\x90\xa9"
#define MAT_SYMBOL_TV "\xee\x8c\xb3"
#define MAT_SYMBOL_VIDEO_SETTINGS "\xee\xa9\xb5"
#define MAT_SYMBOL_WARNING "\xee\x80\x82"
