#pragma once


#define USER_QUIT 100
#define USER_STREAM_OPEN 111
#define USER_STREAM_CLOSE 118
#define USER_STREAM_FINISHED 119
#define USER_SDL_FRAME 120

#define USER_AM_APPLIST_LOADED 201

#define USER_IL_STATE_CHANGED 301
#define USER_IL_IMAGE_DECODED 302
#define USER_ST_QUITAPP_CONFIRM 531

#define USER_INPUT_MOUSE 901
#define USER_INPUT_NAVKEY 902
#define USER_FAKEINPUT_MOUSE_MOTION 951
#define USER_FAKEINPUT_MOUSE_CLICK 952
