#pragma once

#define USER_QUIT 100

#define USER_AM_APPLIST_ARRIVED 201
#define USER_CM_REQ_SERVER_UPDATE 251
#define USER_CM_SERVER_UPDATED 252
#define USER_CM_SERVER_DISCOVERED 253
#define USER_IL_STATE_CHANGED 301
#define USER_IL_IMAGE_DECODED 302
#define USER_ST_QUITAPP_CONFIRM 531

#define USER_INPUT_MOUSE 901