name: Build (Steam Link)

on:
  push:
    # Don't run for tags
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '**'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Set Short Commit ID
        shell: bash
        run: echo SHORT_SHA="${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update Packages
        shell: bash
        run: sudo apt-get -yq update

      - name: Install Steam Link SDK
        uses: ./.github/actions/steamlink-sdk
        with:
          path: .steamlink-sdk

      - name: Install Build Tools
        shell: bash
        run: sudo apt-get -y -qq install cmake gettext

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          source ${{github.workspace}}/.steamlink-sdk/setenv.sh
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        env:
          CMAKE_TOOLCHAIN_FILE: ${{github.workspace}}/.steamlink-sdk/toolchain/steamlink-toolchain.cmake

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          source ${{github.workspace}}/.steamlink-sdk/setenv.sh
          cmake --build . --config $BUILD_TYPE
          cpack

      - name: Add Commit Hash Suffix
        shell: bash
        working-directory: dist
        run: for file in moonlight-tv_*_steamlink.* ; do mv $file ${file//_steamlink/-${SHORT_SHA}_steamlink} ; done

      - name: Copy Install Manual
        run: cp docs/INSTALL.steamlink.md dist/

      - uses: actions/upload-artifact@v4
        with:
          name: steamlink-snapshot-${{ env.SHORT_SHA }}
          path: |
            dist/moonlight-tv_*_steamlink.*
            dist/INSTALL.steamlink.md
