name: Notify Community Discord

on:
  release:
    types: [ released, edited ]
  pull_request:

jobs:
  send-notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event) }}