name: Notify Community Discord

on:
  release:
    types: [ released ]

jobs:
  send-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install jq curl
        env:
          DEBIAN_FRONTEND: 'noninteractive'
      - name: Post Event
        run: |
          curl -X POST -H 'Content-Type: application/json' \ 
            -d $(echo '${{ toJSON(github.event) }}' | jq '.action = "created"') \
            ${{ secrets.DISCORD_NOTIFY_WEBHOOK }}