#pragma once

#define SDL_IS_INPUT_EVENT(evt) (evt.type >= SDL_KEYDOWN && evt.type < SDL_CLIPBOARDUPDATE)
#define SDL_IS_JOYDEVICE_EVENT(evt) (evt.type >= SDL_JOYDEVICEADDED && evt.type <= SDL_JOYDEVICEREMOVED)
#define SDL_IS_CONTROLLERDEVICE_EVENT(evt) (evt.type >= SDL_CONTROLLERDEVICEADDED && evt.type <= SDL_CONTROLLERDEVICEREMAPPED)
#define SDL_IS_JOYSTICK_EVENT(evt) (evt.type >= SDL_JOYAXISMOTION && evt.type <= SDL_JOYDEVICEREMOVED)
#define SDL_IS_GAMECONTROLLER_EVENT(evt) (evt.type >= SDL_CONTROLLERAXISMOTION && evt.type <= SDL_CONTROLLERDEVICEREMAPPED)